### ISSUE TITLE
Structure as a mineflayer plugin

### ISSUE THREAD

**Issue by rom1504** [sefirosweb/minecraftHawkEye#1]
see https://github.com/SiebeDW/mineflayer-tps/blob/master/index.js as example
the idea is to do bot.yourFunction = () => {something}

That means adding things to the bot object rather than wrapping it

**Comment by sefirosweb** [comment]
OK! I check

**Comment by sefirosweb** [comment]
Hi room i update the code to 1.0.5
Now is in loadplugin method

I hope that's what you say =)

**Comment by rom1504** [comment]
yeah, looks good thanks!
just need to fix the mineflayer pr then
