### ISSUE TITLE
Idea: Detect if entity was killed by bot

### ISSUE THREAD

**Issue by DatArnoGuy** [sefirosweb/minecraftHawkEye#14]
Basically idea for new event, which would be triggered if bot kills entity with oneshot or autoattack. Event would return data of entity killed.

Event could be maybe something like this:

bot.on('entity_killed_by_hawkeye', (entity) => {
    console.log(entity);
})

**Comment by DatArnoGuy** [comment]
Other very good event idea similar to this:

entity damaged by hawkeye

bot.on('entity_damaged_by_hawkeye', (entity) => {
console.log('Health of damaged entity: ' + entity.health);
})

**Comment by sefirosweb** [comment]
I take a look!

**Comment by sefirosweb** [comment]
Hi it is not possible to know if the arrow was killed the mob,

But I added a event to detect if the bot are stopped:

![image](https://user-images.githubusercontent.com/20754836/223175570-add608c5-512f-462a-ae43-041c2f315e85.png)

This event is dispatched when mob is dead or when has gone (teleported or goes away)

The event returns the "entity" what are targeting

**Comment by sefirosweb** [comment]
Check if the new version is fine to you
