### ISSUE TITLE
Add a liscense?

### ISSUE THREAD

**Issue by a1cd** [sefirosweb/minecraftHawkEye#15]
There is no liscense on this code, It would be reasurring to have one on this repo, even something in the readme that says "we dont want you doing anything with this code" would be nice.

**Comment by sefirosweb** [comment]
Im new here i prefer no select one for a now,

**Comment by a1cd** [comment]
[github's choosealicense.com](https://choosealicense.com) can help you choose one if you ever change your mind. I am legally at risk if I even try to contribute to your code if you do not have a liscense. I also cannot use your code modified or not. This website can explain better than I can so do check it out.

**Comment by a1cd** [comment]
Also please specify your choice not to choose a liscense in the readme, this helps others a lot.
