### ISSUE TITLE
How to let a robot to automatically equip a bow to a secondary hand for shooting?

### ISSUE THREAD

**Issue by Glasden** [sefirosweb/minecraftHawkEye#23]
I would like the robot to automatically equip the bow to the secondary hand in order to shoot, is there an interface provided for this?Thanks.

**Comment by sefirosweb** [comment]
Nope, this packague is a complement of mineflayer, this package is for calculate the yaw and pitch and also helps to execute shot,
this package dont manage the equip

**Comment by Glasden** [comment]
Thanks for your reply!
