### ISSUE TITLE
add crossbow support

### ISSUE THREAD

**Issue by koneshnoVasya** [sefirosweb/minecraftHawkEye#4]
please

**Comment by sefirosweb** [comment]
You are right :D

Also I want to add support for snowballs + ender perls,

**Comment by sefirosweb** [comment]
Done! (Download / Update lastest version 1.1)

Luckily it is the same equation but changing the startup speed (it is a little higher than the bow 0.15) but this affects the long range attack

Now you need to put 'bow' or 'crossbow' for calculate the grade

```js
bot.hawkEye.getMasterGrade(target, speed, weapon)
```

Also you can use, but I don't recomend you on complex bots
```js
bot.hawkEye.autoAttack(target, weapon) // You can put blockPosition, see example,
// Stop auto attack
bot.hawkEye.stop()
// One Shot
bot.hawkEye.oneshot(target, weapon)
```

Soon I hope add snowballs + ender pell
