### ISSUE TITLE
Add support for crossbow quickcharge enchantment

### ISSUE THREAD

**Issue by linkle69** [sefirosweb/minecraftHawkEye#5]
Make it so if the weapon is a crossbow and has a quick charge enchantment it reevaluates the charge time so the bot can shoot faster

**Comment by sefirosweb** [comment]
Best, I try to get in every tick if already charged,

For avoid different enchant levels issue

**Comment by sefirosweb** [comment]
Done! now is a machine gun!

Could you check with 1.2.1 version?
