### ISSUE TITLE
cannot read height property of mobs

### ISSUE THREAD

**Issue by random-logic** [sefirosweb/minecraftHawkEye#6]
in hawkEyeEquations.js, line 285 throws an error that states "cannot read 'height' of undefined." I changed this line to "targetHeight = target.height" and it works fine after that change. maybe consider changing that line of code on master branch?

thanks!

**Comment by sefirosweb** [comment]
You are right, in the past mineflayer had a bug on target.height but now is solved,

I made a PR and publish a new version 1.1.1 with fix
