### ISSUE TITLE
do snowballs, enderpearls, eggs, etc all use the same formula?

### ISSUE THREAD

**Issue by u9g** [sefirosweb/minecraftHawkEye#7]

**Comment by sefirosweb** [comment]
On it!

*I need to check if they use same formula, maybe only need to change the item gravity and V0 (power of shot)

**Comment by sefirosweb** [comment]
Done!

I update the variables, for lucky use same equations only i need to change the gravity & V0 for each item =)

In 1.2.2 you have full support for all items :D
