### ISSUE TITLE
oneshot gone?

### ISSUE THREAD

**Issue by SinanAkkoyun** [sefirosweb/minecraftHawkEye#8]
I think the oneshot function is not there anymore

**Comment by sefirosweb** [comment]
Hi what you means?

Still exists but the lastest version you can add "weapon" for get correct calcs (bow , crossbow, snowball..)
```js 
bot.hawkEye.oneShot(target, weapon)
```

**Comment by SinanAkkoyun** [comment]
Ohhh, I am so dumb, ofc nodejs showed me there is no oneshot with one parameter :)

Thank you very much, it is very surprising how the bot can completely kill someone with their bow!
